/*put the initial data to be added when the db is created*/
/* --------------- 
	Directors
   --------------- */
INSERT INTO director(lastName) VALUES ('Frank Darabont');
INSERT INTO director(lastName) VALUES ('Francis Ford Coppola');
INSERT INTO director(lastName) VALUES ('Quentin Tarantino');
INSERT INTO director(lastName) VALUES ('Christopher Nolan');
INSERT INTO director(lastName) VALUES ('Steven Spielberg');
INSERT INTO director(lastName) VALUES ('Sidney Lumet');
INSERT INTO director(lastName) VALUES ('Milos Forman');
INSERT INTO director(lastName) VALUES ('Irvin Kershner');
INSERT INTO director(lastName) VALUES ('Peter Jackson');
INSERT INTO director(lastName) VALUES ('George Lucas');
INSERT INTO director(lastName) VALUES ('Martin Scorsese');
INSERT INTO director(lastName) VALUES ('Michael Curtiz');
INSERT INTO director(lastName) VALUES ('David Fincher');
INSERT INTO director(lastName) VALUES ('Alfred Hitchcock');
INSERT INTO director(lastName) VALUES ('Lee Unkrich');
INSERT INTO director(lastName) VALUES ('Bryan Singer');
INSERT INTO director(lastName) VALUES ('Lana Wachowski');
INSERT INTO director(lastName) VALUES ('Lilly Wachowski');
INSERT INTO director(lastName) VALUES ('Jonathan Demme');
INSERT INTO director(lastName) VALUES ('Frank Capra');
INSERT INTO director(lastName) VALUES ('Billy Wilder');
INSERT INTO director(lastName) VALUES ('Stanley Kubrick');
INSERT INTO director(lastName) VALUES ('Robert Zemeckis');
INSERT INTO director(lastName) VALUES ('Orson Welles');
INSERT INTO director(lastName) VALUES ('Sam Mendes');
INSERT INTO director(lastName) VALUES ('Tony Kaye');
INSERT INTO director(lastName) VALUES ('James Cameron');
INSERT INTO director(lastName) VALUES ('Ridley Scott');
INSERT INTO director(lastName) VALUES ('David Lean');
INSERT INTO director(lastName) VALUES ('Robert Mulligan');
INSERT INTO director(lastName) VALUES ('Roman Polanski');
INSERT INTO director(lastName) VALUES ('Charles Chaplin');
INSERT INTO director(lastName) VALUES ('Michel Gondry');
INSERT INTO director(lastName) VALUES ('Darren Aronofsky');
INSERT INTO director(lastName) VALUES ('Wolfgang Petersen');
INSERT INTO director(lastName) VALUES ('Carol Reed');
INSERT INTO director(lastName) VALUES ('Curtis Hanson');
INSERT INTO director(lastName) VALUES ('John Huston');
INSERT INTO director(lastName) VALUES ('Terry Gilliam');
INSERT INTO director(lastName) VALUES ('Terry Jones');
INSERT INTO director(lastName) VALUES ('Stanley Donen');
INSERT INTO director(lastName) VALUES ('Gene Kelly');
INSERT INTO director(lastName) VALUES ('Akira Kurosawa');
INSERT INTO director(lastName) VALUES ('Joseph L. Mankiewicz');
INSERT INTO director(lastName) VALUES ('Sergio Leone');
INSERT INTO director(lastName) VALUES ('Eli Roth');
INSERT INTO director(lastName) VALUES ('Mel Gibson');
INSERT INTO director(lastName) VALUES ('Pete Docter');
INSERT INTO director(lastName) VALUES ('Bob Peterson');
INSERT INTO director(lastName) VALUES ('Kaspar Heidelbach');
INSERT INTO director(lastName) VALUES ('Clint Eastwood');
INSERT INTO director(lastName) VALUES ('Fritz Lang');
INSERT INTO director(lastName) VALUES ('George Roy Hill');
INSERT INTO director(lastName) VALUES ('Frank Miller');
INSERT INTO director(lastName) VALUES ('Robert Rodriguez');
INSERT INTO director(lastName) VALUES ('David Lynch');
INSERT INTO director(lastName) VALUES ('Elia Kazan');
INSERT INTO director(lastName) VALUES ('Richard Marquand');
INSERT INTO director(lastName) VALUES ('John Sturges');
INSERT INTO director(lastName) VALUES ('John McTiernan');
INSERT INTO director(lastName) VALUES ('Terry George');
INSERT INTO director(lastName) VALUES ('Danny Boyle');
INSERT INTO director(lastName) VALUES ('Loveleen Tandan');
INSERT INTO director(lastName) VALUES ('Joel Coen');
INSERT INTO director(lastName) VALUES ('Ethan Coen');
INSERT INTO director(lastName) VALUES ('Michael Mann');
INSERT INTO director(lastName) VALUES ('Clyde Bruckman');
INSERT INTO director(lastName) VALUES ('Buster Keaton');
INSERT INTO director(lastName) VALUES ('Victor Fleming');
INSERT INTO director(lastName) VALUES ('George Cukor');
INSERT INTO director(lastName) VALUES ('Mervyn LeRoy');
INSERT INTO director(lastName) VALUES ('Norman Taurog');
INSERT INTO director(lastName) VALUES ('King Vidor');
INSERT INTO director(lastName) VALUES ('Neill Blomkamp');
INSERT INTO director(lastName) VALUES ('M. Night Shyamalan');
INSERT INTO director(lastName) VALUES ('Guy Ritchie');
INSERT INTO director(lastName) VALUES ('Richard Kelly');
INSERT INTO director(lastName) VALUES ('Woody Allen');
INSERT INTO director(lastName) VALUES ('Michael Cimino');
INSERT INTO director(lastName) VALUES ('Stuart Rosenberg');
INSERT INTO director(lastName) VALUES ('Fred Zinnemann');
INSERT INTO director(lastName) VALUES ('Oliver Stone');
INSERT INTO director(lastName) VALUES ('Roger Allers');
INSERT INTO director(lastName) VALUES ('Rob Minkoff');
INSERT INTO director(lastName) VALUES ('Sean Penn');
INSERT INTO director(lastName) VALUES ('Paul Thomas Anderson');
INSERT INTO director(lastName) VALUES ('John Lasseter');
INSERT INTO director(lastName) VALUES ('Sam Wood');
INSERT INTO director(lastName) VALUES ('William Wyler');
INSERT INTO director(lastName) VALUES ('Brian De Palma');
INSERT INTO director(lastName) VALUES ('John Ford');
INSERT INTO director(lastName) VALUES ('Mike Nichols');
INSERT INTO director(lastName) VALUES ('Howard Hawks');
INSERT INTO director(lastName) VALUES ('Harold Ramis');
INSERT INTO director(lastName) VALUES ('Paul Greengrass');
INSERT INTO director(lastName) VALUES ('Andrew Stanton');
INSERT INTO director(lastName) VALUES ('Rob Reiner');
INSERT INTO director(lastName) VALUES ('Dean DeBlois');
INSERT INTO director(lastName) VALUES ('Chris Sanders');
INSERT INTO director(lastName) VALUES ('John Carpenter');
INSERT INTO director(lastName) VALUES ('James McTeigue');
INSERT INTO director(lastName) VALUES ('Martin Campbell');
INSERT INTO director(lastName) VALUES ('Brad Bird');
INSERT INTO director(lastName) VALUES ('Jan Pinkava');
INSERT INTO director(lastName) VALUES ('Richard Attenborough');
INSERT INTO director(lastName) VALUES ('J.J. Abrams');
INSERT INTO director(lastName) VALUES ('Charles Laughton');
INSERT INTO director(lastName) VALUES ('Robert Mitchum');
INSERT INTO director(lastName) VALUES ('Terry Sanders');
INSERT INTO director(lastName) VALUES ('Stanley Kramer');
INSERT INTO director(lastName) VALUES ('Robert Rossen');
INSERT INTO director(lastName) VALUES ('Gus Van Sant');
INSERT INTO director(lastName) VALUES ('N/A');
INSERT INTO director(lastName) VALUES ('Martin McDonagh');
INSERT INTO director(lastName) VALUES ('Sam Peckinpah');
INSERT INTO director(lastName) VALUES ('Federico Fellini');
INSERT INTO director(lastName) VALUES ('William Friedkin');
INSERT INTO director(lastName) VALUES ('Ingmar Bergman');
INSERT INTO director(lastName) VALUES ('Tim Burton');
INSERT INTO director(lastName) VALUES ('Lewis Milestone');
INSERT INTO director(lastName) VALUES ('John G. Avildsen');
INSERT INTO director(lastName) VALUES ('Robert Hamer');
INSERT INTO director(lastName) VALUES ('Adam Elliot');
INSERT INTO director(lastName) VALUES ('Franklin J. Schaffner');
INSERT INTO director(lastName) VALUES ('Leo McCarey');
INSERT INTO director(lastName) VALUES ('Matthew Vaughn');
INSERT INTO director(lastName) VALUES ('Gore Verbinski');
INSERT INTO director(lastName) VALUES ('Peter Weir');
INSERT INTO director(lastName) VALUES ('Henry Koster');
INSERT INTO director(lastName) VALUES ('Bob Clark');
INSERT INTO director(lastName) VALUES ('David Silverman');


/* --------------- 
	Topics
   --------------- */
INSERT INTO topics(description) VALUES ('horror');
INSERT INTO topics(description) VALUES ('action');
INSERT INTO topics(description) VALUES ('Crime');
INSERT INTO topics(description) VALUES ('Drama');
INSERT INTO topics(description) VALUES ('Action');
INSERT INTO topics(description) VALUES ('Mystery');
INSERT INTO topics(description) VALUES ('Sci-Fi');
INSERT INTO topics(description) VALUES ('Biography');
INSERT INTO topics(description) VALUES ('History');
INSERT INTO topics(description) VALUES ('Adventure');
INSERT INTO topics(description) VALUES ('Fantasy');
INSERT INTO topics(description) VALUES ('Romance');
INSERT INTO topics(description) VALUES ('War');
INSERT INTO topics(description) VALUES ('Thriller');
INSERT INTO topics(description) VALUES ('Animation');
INSERT INTO topics(description) VALUES ('Comedy');
INSERT INTO topics(description) VALUES ('Horror');
INSERT INTO topics(description) VALUES ('Family');
INSERT INTO topics(description) VALUES ('Film-Noir');
INSERT INTO topics(description) VALUES ('Sport');
INSERT INTO topics(description) VALUES ('Musical');
INSERT INTO topics(description) VALUES ('Music');
INSERT INTO topics(description) VALUES ('Western');

/* --------------- 
	Movie titles
   --------------- */
INSERT INTO movie(name, dateReleased) VALUES ('The Shawshank Redemption', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('The Godfather', 1972);
INSERT INTO movie(name, dateReleased) VALUES ('The Godfather: Part II', 1974);
INSERT INTO movie(name, dateReleased) VALUES ('Il buono, il brutto, il cattivo.', 1966);
INSERT INTO movie(name, dateReleased) VALUES ('Pulp Fiction', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('Inception', 2010);
INSERT INTO movie(name, dateReleased) VALUES ('Schindler''s List', 1993);
INSERT INTO movie(name, dateReleased) VALUES ('12 Angry Men', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('One Flew Over the Cuckoo''s Nest', 1975);
INSERT INTO movie(name, dateReleased) VALUES ('The Dark Knight', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('Star Wars: Episode V - The Empire Strikes Back', 1980);
INSERT INTO movie(name, dateReleased) VALUES ('The Lord of the Rings: The Return of the King', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('Shichinin no samurai', 1954);
INSERT INTO movie(name, dateReleased) VALUES ('Star Wars', 1977);
INSERT INTO movie(name, dateReleased) VALUES ('Goodfellas', 1990);
INSERT INTO movie(name, dateReleased) VALUES ('Casablanca', 1942);
INSERT INTO movie(name, dateReleased) VALUES ('Fight Club', 1999);
INSERT INTO movie(name, dateReleased) VALUES ('Cidade de Deus', 2002);
INSERT INTO movie(name, dateReleased) VALUES ('The Lord of the Rings: The Fellowship of the Ring', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('Rear Window', 1954);
INSERT INTO movie(name, dateReleased) VALUES ('C''era una volta il West', 1968);
INSERT INTO movie(name, dateReleased) VALUES ('Raiders of the Lost Ark', 1981);
INSERT INTO movie(name, dateReleased) VALUES ('Toy Story 3', 2010);
INSERT INTO movie(name, dateReleased) VALUES ('Psycho', 1960);
INSERT INTO movie(name, dateReleased) VALUES ('The Usual Suspects', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('The Matrix', 1999);
INSERT INTO movie(name, dateReleased) VALUES ('The Silence of the Lambs', 1991);
INSERT INTO movie(name, dateReleased) VALUES ('Se7en', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('Memento', 2000);
INSERT INTO movie(name, dateReleased) VALUES ('It''s a Wonderful Life', 1946);
INSERT INTO movie(name, dateReleased) VALUES ('The Lord of the Rings: The Two Towers', 2002);
INSERT INTO movie(name, dateReleased) VALUES ('Sunset Blvd.', 1950);
INSERT INTO movie(name, dateReleased) VALUES ('Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 1964);
INSERT INTO movie(name, dateReleased) VALUES ('Forrest Gump', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('Léon', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('Citizen Kane', 1941);
INSERT INTO movie(name, dateReleased) VALUES ('Apocalypse Now', 1979);
INSERT INTO movie(name, dateReleased) VALUES ('North by Northwest', 1959);
INSERT INTO movie(name, dateReleased) VALUES ('American Beauty', 1999);
INSERT INTO movie(name, dateReleased) VALUES ('American History X', 1998);
INSERT INTO movie(name, dateReleased) VALUES ('Taxi Driver', 1976);
INSERT INTO movie(name, dateReleased) VALUES ('Terminator 2: Judgment Day', 1991);
INSERT INTO movie(name, dateReleased) VALUES ('Saving Private Ryan', 1998);
INSERT INTO movie(name, dateReleased) VALUES ('Vertigo', 1958);
INSERT INTO movie(name, dateReleased) VALUES ('Le fabuleux destin d''Amélie Poulain', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('Alien', 1979);
INSERT INTO movie(name, dateReleased) VALUES ('WALL·E', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('Lawrence of Arabia', 1962);
INSERT INTO movie(name, dateReleased) VALUES ('The Shining', 1980);
INSERT INTO movie(name, dateReleased) VALUES ('Sen to Chihiro no kamikakushi', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('Paths of Glory', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('A Clockwork Orange', 1971);
INSERT INTO movie(name, dateReleased) VALUES ('Double Indemnity', 1944);
INSERT INTO movie(name, dateReleased) VALUES ('To Kill a Mockingbird', 1962);
INSERT INTO movie(name, dateReleased) VALUES ('The Pianist', 2002);
INSERT INTO movie(name, dateReleased) VALUES ('Das Leben der Anderen', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('The Departed', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('M', 1931);
INSERT INTO movie(name, dateReleased) VALUES ('City Lights', 1931);
INSERT INTO movie(name, dateReleased) VALUES ('Aliens', 1986);
INSERT INTO movie(name, dateReleased) VALUES ('Eternal Sunshine of the Spotless Mind', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Requiem for a Dream', 2000);
INSERT INTO movie(name, dateReleased) VALUES ('Das Boot', 1981);
INSERT INTO movie(name, dateReleased) VALUES ('The Third Man', 1949);
INSERT INTO movie(name, dateReleased) VALUES ('L.A. Confidential', 1997);
INSERT INTO movie(name, dateReleased) VALUES ('Reservoir Dogs', 1992);
INSERT INTO movie(name, dateReleased) VALUES ('Chinatown', 1974);
INSERT INTO movie(name, dateReleased) VALUES ('The Treasure of the Sierra Madre', 1948);
INSERT INTO movie(name, dateReleased) VALUES ('Modern Times', 1936);
INSERT INTO movie(name, dateReleased) VALUES ('Monty Python and the Holy Grail', 1975);
INSERT INTO movie(name, dateReleased) VALUES ('La vita è bella', 1997);
INSERT INTO movie(name, dateReleased) VALUES ('Back to the Future', 1985);
INSERT INTO movie(name, dateReleased) VALUES ('The Prestige', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('El laberinto del fauno', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('Raging Bull', 1980);
INSERT INTO movie(name, dateReleased) VALUES ('Nuovo Cinema Paradiso', 1988);
INSERT INTO movie(name, dateReleased) VALUES ('Singin'' in the Rain', 1952);
INSERT INTO movie(name, dateReleased) VALUES ('Some Like It Hot', 1959);
INSERT INTO movie(name, dateReleased) VALUES ('The Bridge on the River Kwai', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('Rashômon', 1950);
INSERT INTO movie(name, dateReleased) VALUES ('All About Eve', 1950);
INSERT INTO movie(name, dateReleased) VALUES ('Amadeus', 1984);
INSERT INTO movie(name, dateReleased) VALUES ('Once Upon a Time in America', 1984);
INSERT INTO movie(name, dateReleased) VALUES ('The Green Mile', 1999);
INSERT INTO movie(name, dateReleased) VALUES ('Full Metal Jacket', 1987);
INSERT INTO movie(name, dateReleased) VALUES ('Inglourious Basterds', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('2001: A Space Odyssey', 1968);
INSERT INTO movie(name, dateReleased) VALUES ('The Great Dictator', 1940);
INSERT INTO movie(name, dateReleased) VALUES ('Braveheart', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('Ladri di biciclette', 1948);
INSERT INTO movie(name, dateReleased) VALUES ('The Apartment', 1960);
INSERT INTO movie(name, dateReleased) VALUES ('Up', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('Der Untergang', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Gran Torino', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('Metropolis', 1927);
INSERT INTO movie(name, dateReleased) VALUES ('The Sting', 1973);
INSERT INTO movie(name, dateReleased) VALUES ('Gladiator', 2000);
INSERT INTO movie(name, dateReleased) VALUES ('The Maltese Falcon', 1941);
INSERT INTO movie(name, dateReleased) VALUES ('Unforgiven', 1992);
INSERT INTO movie(name, dateReleased) VALUES ('Sin City', 2005);
INSERT INTO movie(name, dateReleased) VALUES ('The Elephant Man', 1980);
INSERT INTO movie(name, dateReleased) VALUES ('Mr. Smith Goes to Washington', 1939);
INSERT INTO movie(name, dateReleased) VALUES ('Oldeuboi', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('On the Waterfront', 1954);
INSERT INTO movie(name, dateReleased) VALUES ('Indiana Jones and the Last Crusade', 1989);
INSERT INTO movie(name, dateReleased) VALUES ('Star Wars: Episode VI - Return of the Jedi', 1983);
INSERT INTO movie(name, dateReleased) VALUES ('Rebecca', 1940);
INSERT INTO movie(name, dateReleased) VALUES ('The Great Escape', 1963);
INSERT INTO movie(name, dateReleased) VALUES ('Die Hard', 1988);
INSERT INTO movie(name, dateReleased) VALUES ('Batman Begins', 2005);
INSERT INTO movie(name, dateReleased) VALUES ('Mononoke-hime', 1997);
INSERT INTO movie(name, dateReleased) VALUES ('Jaws', 1975);
INSERT INTO movie(name, dateReleased) VALUES ('Hotel Rwanda', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Slumdog Millionaire', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('Det sjunde inseglet', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('Blade Runner', 1982);
INSERT INTO movie(name, dateReleased) VALUES ('Fargo', 1996);
INSERT INTO movie(name, dateReleased) VALUES ('No Country for Old Men', 2007);
INSERT INTO movie(name, dateReleased) VALUES ('Heat', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('The General', 1926);
INSERT INTO movie(name, dateReleased) VALUES ('The Wizard of Oz', 1939);
INSERT INTO movie(name, dateReleased) VALUES ('Touch of Evil', 1958);
INSERT INTO movie(name, dateReleased) VALUES ('Per qualche dollaro in più', 1965);
INSERT INTO movie(name, dateReleased) VALUES ('Ran', 1985);
INSERT INTO movie(name, dateReleased) VALUES ('Yôjinbô', 1961);
INSERT INTO movie(name, dateReleased) VALUES ('District 9', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('The Sixth Sense', 1999);
INSERT INTO movie(name, dateReleased) VALUES ('Snatch.', 2000);
INSERT INTO movie(name, dateReleased) VALUES ('Donnie Darko', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('Annie Hall', 1977);
INSERT INTO movie(name, dateReleased) VALUES ('Witness for the Prosecution', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('Smultronstället', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('The Deer Hunter', 1978);
INSERT INTO movie(name, dateReleased) VALUES ('Avatar', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('The Social Network', 2010);
INSERT INTO movie(name, dateReleased) VALUES ('Cool Hand Luke', 1967);
INSERT INTO movie(name, dateReleased) VALUES ('Strangers on a Train', 1951);
INSERT INTO movie(name, dateReleased) VALUES ('High Noon', 1952);
INSERT INTO movie(name, dateReleased) VALUES ('The Big Lebowski', 1998);
INSERT INTO movie(name, dateReleased) VALUES ('Hotaru no haka', 1988);
INSERT INTO movie(name, dateReleased) VALUES ('Kill Bill: Vol. 1', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('It Happened One Night', 1934);
INSERT INTO movie(name, dateReleased) VALUES ('Platoon', 1986);
INSERT INTO movie(name, dateReleased) VALUES ('The Lion King', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('Into the Wild', 2007);
INSERT INTO movie(name, dateReleased) VALUES ('There Will Be Blood', 2007);
INSERT INTO movie(name, dateReleased) VALUES ('Notorious', 1946);
INSERT INTO movie(name, dateReleased) VALUES ('Million Dollar Baby', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Toy Story', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('Butch Cassidy and the Sundance Kid', 1969);
INSERT INTO movie(name, dateReleased) VALUES ('Gone with the Wind', 1939);
INSERT INTO movie(name, dateReleased) VALUES ('Sunrise: A Song of Two Humans', 1927);
INSERT INTO movie(name, dateReleased) VALUES ('The Wrestler', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('The Manchurian Candidate', 1962);
INSERT INTO movie(name, dateReleased) VALUES ('Trainspotting', 1996);
INSERT INTO movie(name, dateReleased) VALUES ('Ben-Hur', 1959);
INSERT INTO movie(name, dateReleased) VALUES ('Scarface', 1983);
INSERT INTO movie(name, dateReleased) VALUES ('The Grapes of Wrath', 1940);
INSERT INTO movie(name, dateReleased) VALUES ('The Graduate', 1967);
INSERT INTO movie(name, dateReleased) VALUES ('The Big Sleep', 1946);
INSERT INTO movie(name, dateReleased) VALUES ('Groundhog Day', 1993);
INSERT INTO movie(name, dateReleased) VALUES ('Life of Brian', 1979);
INSERT INTO movie(name, dateReleased) VALUES ('The Gold Rush', 1925);
INSERT INTO movie(name, dateReleased) VALUES ('The Bourne Ultimatum', 2007);
INSERT INTO movie(name, dateReleased) VALUES ('Amores perros', 2000);
INSERT INTO movie(name, dateReleased) VALUES ('Finding Nemo', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('The Terminator', 1984);
INSERT INTO movie(name, dateReleased) VALUES ('Stand by Me', 1986);
INSERT INTO movie(name, dateReleased) VALUES ('How to Train Your Dragon', 2010);
INSERT INTO movie(name, dateReleased) VALUES ('The Best Years of Our Lives', 1946);
INSERT INTO movie(name, dateReleased) VALUES ('Lock, Stock and Two Smoking Barrels', 1998);
INSERT INTO movie(name, dateReleased) VALUES ('The Thing', 1982);
INSERT INTO movie(name, dateReleased) VALUES ('The Kid', 1921);
INSERT INTO movie(name, dateReleased) VALUES ('V for Vendetta', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('Casino', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('Twelve Monkeys', 1995);
INSERT INTO movie(name, dateReleased) VALUES ('Dog Day Afternoon', 1975);
INSERT INTO movie(name, dateReleased) VALUES ('Ratatouille', 2007);
INSERT INTO movie(name, dateReleased) VALUES ('El secreto de sus ojos', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('Gandhi', 1982);
INSERT INTO movie(name, dateReleased) VALUES ('Star Trek', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('Ikiru', 1952);
INSERT INTO movie(name, dateReleased) VALUES ('Le salaire de la peur', 1953);
INSERT INTO movie(name, dateReleased) VALUES ('Les diaboliques', 1955);
INSERT INTO movie(name, dateReleased) VALUES ('8½', 1963);
INSERT INTO movie(name, dateReleased) VALUES ('The Princess Bride', 1987);
INSERT INTO movie(name, dateReleased) VALUES ('The Night of the Hunter', 1955);
INSERT INTO movie(name, dateReleased) VALUES ('Judgment at Nuremberg', 1961);
INSERT INTO movie(name, dateReleased) VALUES ('The Incredibles', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Tonari no Totoro', 1988);
INSERT INTO movie(name, dateReleased) VALUES ('The Hustler', 1961);
INSERT INTO movie(name, dateReleased) VALUES ('Good Will Hunting', 1997);
INSERT INTO movie(name, dateReleased) VALUES ('The Killing', 1956);
INSERT INTO movie(name, dateReleased) VALUES ('In Bruges', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('The Wild Bunch', 1969);
INSERT INTO movie(name, dateReleased) VALUES ('Network', 1976);
INSERT INTO movie(name, dateReleased) VALUES ('Le scaphandre et le papillon', 2007);
INSERT INTO movie(name, dateReleased) VALUES ('A Streetcar Named Desire', 1951);
INSERT INTO movie(name, dateReleased) VALUES ('Les quatre cents coups', 1959);
INSERT INTO movie(name, dateReleased) VALUES ('La strada', 1954);
INSERT INTO movie(name, dateReleased) VALUES ('The Exorcist', 1973);
INSERT INTO movie(name, dateReleased) VALUES ('Children of Men', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('Stalag 17', 1953);
INSERT INTO movie(name, dateReleased) VALUES ('Persona', 1966);
INSERT INTO movie(name, dateReleased) VALUES ('Who''s Afraid of Virginia Woolf?', 1966);
INSERT INTO movie(name, dateReleased) VALUES ('Ed Wood', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('Dial M for Murder', 1954);
INSERT INTO movie(name, dateReleased) VALUES ('La battaglia di Algeri', 1966);
INSERT INTO movie(name, dateReleased) VALUES ('Låt den rätte komma in', 2008);
INSERT INTO movie(name, dateReleased) VALUES ('All Quiet on the Western Front', 1930);
INSERT INTO movie(name, dateReleased) VALUES ('Big Fish', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('Magnolia', 1999);
INSERT INTO movie(name, dateReleased) VALUES ('Rocky', 1976);
INSERT INTO movie(name, dateReleased) VALUES ('La passion de Jeanne d''Arc', 1928);
INSERT INTO movie(name, dateReleased) VALUES ('Kind Hearts and Coronets', 1949);
INSERT INTO movie(name, dateReleased) VALUES ('Fanny och Alexander', 1982);
INSERT INTO movie(name, dateReleased) VALUES ('Mystic River', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('Manhattan', 1979);
INSERT INTO movie(name, dateReleased) VALUES ('Barry Lyndon', 1975);
INSERT INTO movie(name, dateReleased) VALUES ('Kill Bill: Vol. 2', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Mary and Max', 2009);
INSERT INTO movie(name, dateReleased) VALUES ('Patton', 1970);
INSERT INTO movie(name, dateReleased) VALUES ('Rosemary''s Baby', 1968);
INSERT INTO movie(name, dateReleased) VALUES ('Duck Soup', 1933);
INSERT INTO movie(name, dateReleased) VALUES ('Festen', 1998);
INSERT INTO movie(name, dateReleased) VALUES ('Kick-Ass', 2010);
INSERT INTO movie(name, dateReleased) VALUES ('Letters from Iwo Jima', 2006);
INSERT INTO movie(name, dateReleased) VALUES ('Roman Holiday', 1953);
INSERT INTO movie(name, dateReleased) VALUES ('Pirates of the Caribbean: The Curse of the Black Pearl', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('Mou gaan dou', 2002);
INSERT INTO movie(name, dateReleased) VALUES ('The Truman Show', 1998);
INSERT INTO movie(name, dateReleased) VALUES ('Crash', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('Hauru no ugoku shiro', 2004);
INSERT INTO movie(name, dateReleased) VALUES ('His Girl Friday', 1940);
INSERT INTO movie(name, dateReleased) VALUES ('Arsenic and Old Lace', 1944);
INSERT INTO movie(name, dateReleased) VALUES ('Harvey', 1950);
INSERT INTO movie(name, dateReleased) VALUES ('Le notti di Cabiria', 1957);
INSERT INTO movie(name, dateReleased) VALUES ('Trois couleurs: Rouge', 1994);
INSERT INTO movie(name, dateReleased) VALUES ('The Philadelphia Story', 1940);
INSERT INTO movie(name, dateReleased) VALUES ('A Christmas Story', 1983);
INSERT INTO movie(name, dateReleased) VALUES ('Sleuth', 1972);
INSERT INTO movie(name, dateReleased) VALUES ('King Kong', 1933);
INSERT INTO movie(name, dateReleased) VALUES ('Bom yeoreum gaeul gyeoul geurigo bom', 2003);
INSERT INTO movie(name, dateReleased) VALUES ('Rope', 1948);
INSERT INTO movie(name, dateReleased) VALUES ('Monsters, Inc.', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('Tenkû no shiro Rapyuta', 1986);
INSERT INTO movie(name, dateReleased) VALUES ('Yeopgijeogin geunyeo', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('Mulholland Dr.', 2001);
INSERT INTO movie(name, dateReleased) VALUES ('The Man Who Shot Liberty Valance', 1962);

/* --------------- 
	User names
   --------------- */
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Mariam', 'Massenburg', '10101010', 'Mariam@Massenburg.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Laurine', 'Greiner', '7777', 'Laurine@Greiner.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Sydney', 'Foret', '5555', 'Sydney@Foret.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Elissa', 'Vanasse', '7777', 'Elissa@Vanasse.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Angella', 'Duclos', '6666', 'Angella@Duclos.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Johnny', 'Fells', '5555', 'Johnny@Fells.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Tereasa', 'Wise', '4444', 'Tereasa@Wise.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Irma', 'Neher', '5555', 'Irma@Neher.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Cyrus', 'Janson', '6666', 'Cyrus@Janson.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Chasity', 'Gregson', '7777', 'Chasity@Gregson.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Angelica', 'Jerabek', '7777', 'Angelica@Jerabek.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Caprice', 'Sandford', '8888', 'Caprice@Sandford.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Blair', 'Whitmarsh', '9999', 'Blair@Whitmarsh.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Lakisha', 'Iskra', '5555', 'Lakisha@Iskra.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Penney', 'Greenleaf', '9999', 'Penney@Greenleaf.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Josette', 'Corby', '5555', 'Josette@Corby.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Audie', 'Tyner', '5555', 'Audie@Tyner.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Aida', 'Ek', '2222', 'Aida@Ek.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Jackelyn', 'Pankey', '6666', 'Jackelyn@Pankey.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Raelene', 'Tomas', '5555', 'Raelene@Tomas.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Ellsworth', 'Stegman', '7777', 'Ellsworth@Stegman.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Nanette', 'Oakes', '5555', 'Nanette@Oakes.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Josephine', 'Filip', '5555', 'Josephine@Filip.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Audra', 'Hatmaker', '8888', 'Audra@Hatmaker.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Fairy', 'Yocom', '5555', 'Fairy@Yocom.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Carey', 'Carwile', '7777', 'Carey@Carwile.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Shonta', 'Ryburn', '6666', 'Shonta@Ryburn.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Amy', 'Stribling', '9999', 'Amy@Stribling.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Delana', 'Crisp', '5555', 'Delana@Crisp.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Buffy', 'Minchew', '7777', 'Buffy@Minchew.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Damon', 'Steuck', '6666', 'Damon@Steuck.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Junie', 'Cacciatore', '10101010', 'Junie@Cacciatore.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Fae', 'Downey', '6666', 'Fae@Downey.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Davis', 'Bence', '5555', 'Davis@Bence.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Francoise', 'Crosson', '7777', 'Francoise@Crosson.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Sylvester', 'Howie', '5555', 'Sylvester@Howie.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Armandina', 'Mcbeth', '6666', 'Armandina@Mcbeth.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Ann', 'Devillier', '9999', 'Ann@Devillier.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Keneth', 'Fuerst', '6666', 'Keneth@Fuerst.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Lorrie', 'Simoneaux', '9999', 'Lorrie@Simoneaux.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Pedro', 'Grana', '5555', 'Pedro@Grana.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Windy', 'Beauchemin', '10101010', 'Windy@Beauchemin.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Burma', 'Mclaughin', '9999', 'Burma@Mclaughin.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Mia', 'Straube', '7777', 'Mia@Straube.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Steffanie', 'Ying', '4444', 'Steffanie@Ying.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Willia', 'Montalvan', '9999', 'Willia@Montalvan.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Kiley', 'Halpern', '7777', 'Kiley@Halpern.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Marcos', 'Spillers', '8888', 'Marcos@Spillers.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Dominic', 'Leedy', '5555', 'Dominic@Leedy.com');
INSERT INTO movieUser(firstName, lastName, password, email) VALUES ('Renita', 'Kirklin', '7777', 'Renita@Kirklin.com');
